import time
from selenium import webdriver
from selenium.webdriver.support.ui import Select
driver=webdriver.Firefox()
search=driver.get("http://uat.reachsafe.co.in/SheShuttle/logout.html")
search1=driver.find_element_by_id("userInput").send_keys("nikhil.tumiki@votarytech.com")
search2=driver.find_element_by_id("passwordInput").send_keys("nikhil")
serach3=driver.find_element_by_id("login-button").click()
search4=driver.find_element_by_class_name("highlite").click()
time.sleep(1)
select2=driver.find_element_by_class_name("dropdown").click()
time.sleep(1)
select3=driver.find_element_by_link_text("Summary").click()
time.sleep(1)
select=driver.find_element_by_class_name("dropdown").click()
time.sleep(1)
reports=driver.find_element_by_link_text("Reports").click()
time.sleep(1)
select2=driver.find_element_by_class_name("dropdown").click()
time.sleep(1)
feedbacks=driver.find_element_by_link_text("Feedbacks").click()
time.sleep(1)
select2=driver.find_element_by_class_name("dropdown").click()
time.sleep(1)
user=driver.find_element_by_link_text("User Alerts").click()
time.sleep(1)
#select2=driver.find_element_by_class_name("dropdown").click()
#time.sleep(1)
#company=driver.find_element_by_link_text("company wise users").click()


Regi=driver.find_element_by_link_text("Registration").click()
time.sleep(1)
route=driver.find_element_by_link_text("Route").click()
time.sleep(2)
regi=driver.find_element_by_link_text("Registration").click()
time.sleep(2)
regi=driver.find_element_by_link_text("Vehicle").click()
time.sleep(2)
regi=driver.find_element_by_link_text("Registration").click()
time.sleep(2)
driver=driver.find_element_by_link_text("Driver").click()
time.sleep(2)
regi=driver.find_element_by_link_text("Registration").click()
time.sleep(2)
security=driver.find_element_by_link_text("Security").click()
time.sleep(2)
regi=driver.find_element_by_link_text("Registration").click()
time.sleep(2)
company=driver.find_element_by_link_text("Company").click()
time.sleep(2)
regi=driver.find_element_by_link_text("Registration").click()
time.sleep(2)
company=driver.find_element_by_link_text("Company").click()
time.sleep(2)
regi=driver.find_element_by_link_text("Registration").click()
time.sleep(2)
company=driver.find_element_by_link_text("Company").click()
time.sleep(2)

